# PHP-FPM 8.4 (Alpine)
FROM php:8.4-fpm-alpine

# Pacotes úteis mínimos
RUN apk add --no-cache bash tzdata

# Opcache (opcional mas recomendado)
RUN docker-php-ext-install opcache

# Timezone
ENV TZ=America/Bahia
RUN echo "date.timezone=${TZ}" > /usr/local/etc/php/conf.d/timezone.ini

# Hardening básico (opcional)
RUN { \
      echo "cgi.fix_pathinfo=0"; \
      echo "opcache.enable=1"; \
      echo "opcache.enable_cli=1"; \
      echo "opcache.memory_consumption=128"; \
      echo "opcache.max_accelerated_files=10000"; \
    } > /usr/local/etc/php/conf.d/custom.ini

# Composer (útil para libs futuras)
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Diretório de trabalho dentro do container
WORKDIR /var/www/html
 

EXPOSE 9000
CMD ["php-fpm", "-F"]
