services:
  app:
    build: .
    container_name: quickmessage-php
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      TZ: America/Bahia
    networks:
      - appnet

  nginx:
    image: nginx:1.27-alpine
    container_name: quickmessage-nginx
    ports:
      - "8080:80"                    # Acesse em http://localhost:8080
    volumes:
      - ./:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
