

services:
  nginx:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./src:/var/www/html:rw
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - helpdesk-network

  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_UID: "${APP_UID:-1000}"
        APP_GID: "${APP_GID:-1000}"
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html:rw
    user: "${APP_UID:-1000}:${APP_GID:-1000}"
    networks:
      - helpdesk-network

networks:
  helpdesk-network:
    driver: bridge
